/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 3;
=======
const int buildversion = 16;
>>>>>>> 1afe8fd744553e97ca11771a1894fcea398d85f9
const char buildconfig[] = "DUMBVM";
